# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format : json
    include_format: false
  format_listener:
      rules:
        - { path: '^/api', priorities: ['json'], fallback_format: json }
        - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
  exception:
      enabled: true
  view:
      view_response_listener: 'force'
      formats:
        json: true

